# set base image
FROM python:3.6.14-slim-buster

# image description
LABEL name="Container image with Jupyter and Ludwig"

# set the working directory in the container
WORKDIR /MyLudwig

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip3 install -U pip
RUN pip3 install -r requirements.txt

# copy a local directory into the container
COPY ./MyLudwig ./MyLudwig

# Prepare jupyter notebook
EXPOSE 8888
CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--allow-root", "--ip=0.0.0.0"]