input_features:
    -
        name: worst_concave_points
        type: numerical
        encoder: dense
        preprocessing:
            normalization: zscore
    -
        name: worst_perimeter
        type: numerical
        encoder: dense
        preprocessing:
            normalization: zscore
    -
        name: mean_concave_points
        type: numerical
        encoder: dense
        preprocessing:
            normalization: zscore
 
output_features:
    -
        name: label
        type: binary

training:
        batch_size: 64
        epochs: 80