FROM tensorflow/tensorflow:latest-jupyter

LABEL name="Container with Jupyter, Tensorflow-Quantum and Cirq"
LABEL description="This container will be used by every participant of the Quantum Computing Hackathon."

WORKDIR /Python/NeuralNetworks/Tensorflow-Quantum

RUN pip3 install -U pip
RUN pip3 install -q tensorflow==2.3.1
RUN pip3 install -U tensorflow-quantum
RUN pip3 install -U seaborn
RUN pip3 install -U matplotlib
RUN pip3 install -U cirq