FROM jupyter/datascience-notebook:latest

LABEL name="Container image with Jupyter, Tensorflow, Tensorflow-Quantum and Cirq"
LABEL description="This container image will be used by every participant of the Quantum Computing Hackathon."

WORKDIR /Tensorflow-Quantum

COPY ./breast_cancer_dataset.csv .

RUN pip3 install -U pip
RUN pip3 install tensorflow==2.3.1
RUN pip3 install -U tensorflow-quantum
RUN pip3 install -U seaborn
RUN pip3 install -U matplotlib
RUN pip3 install -U cirq