# set base image
FROM jupyter/minimal-notebook

# image description
LABEL name="Container image with Jupyter Notebook and Fast AI"

# set the working directory in the container
WORKDIR /MyFastAI

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip3 install -U pip
RUN pip3 install -r requirements.txt

# copy a local directory into the container
COPY ./MyFastAI ./MyFastAI
